version: '3.1'

services:
  
  postgres:
    image: postgres:13.1
    container_name: nestjs_db-connection-postgres-nestjs_db
    restart: always
    environment:
      POSTGRES_USER: mohyaldeen
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: nestjs_db
    volumes:
      - nestjs_postgres_db:/data/postgres

    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: nestjs-db-connection-adminer
    restart: always
    ports:
      - 8080:8080  


volumes:
  nestjs_postgres_db:            
